Pull analytics from linked fields in webflow
offerzen/webflow pull request #16
Opened 2022-04-22 13:11 UTC by michael616kriel

https://offerzen.atlassian.net/jira/software/projects/GPS/boards/4?assignee=61309abdac61dc00696a26e4&selectedIssue=GPS-93
<img width="242" alt="Screenshot 2022-04-22 at 15 11 30" src="https://user-images.githubusercontent.com/23308191/164720921-fde7347d-5132-43c0-88f6-de610fd97900.png">
7

2022-04-22 13:34 UTC, MarkusKuhn approved these changes
Nice one @michael616kriel !

2022-04-22 13:34 UTC, MarkusKuhn commented on offerzen/global/employers/employers@4.0.js
> +        event: event || 'Company Lead Form Submitted ',
@michael616kriel nice one on the defaults here! 👌

2022-04-25 06:42 UTC, jethroflanagan requested changes
Looks good, please just drop the space on one of the defaults.

2022-04-25 06:42 UTC, jethroflanagan commented on offerzen/global/employers/employers@4.0.js
> +        event: event || 'Company Lead Form Submitted ',
```suggestion
        event: event || 'Company Lead Form Submitted',
```

2022-04-25 12:24 UTC, jethroflanagan approved these changes

2022-04-28 07:38 UTC, merged