Community Activity Submission Handler
offerzen/webflow pull request #24
Opened 2022-07-15 13:36 UTC by MarkusKuhn

**What**
  - Added script to handle any form of community activity submission which:
    - Checks and collects all required values such as first name, last name, email
    - Checks for and collects any extra fields which may be required by a growth form, as well as email subscription checkbox values
    - Removes default form submission binding provided by webflow in order to add custom form submission handler, and thus submission to the community activities controller
    - Includes support for reCAPTCHA
    - Handles error states by displaying webflow default error state
    - Updates submission button text on form submission, and preserves original text value, to switch back to original on successful or failed form submission

2022-07-15 14:15 UTC, jethroflanagan requested changes
Some feedback on a few things

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +        var textField = document.querySelector("#" + fields[i]);
Would recommend not using IDs here, but referencing it by name instead `input[name="${fields[i]}"]`

Even if IDs are preferred, then scope it to `form` and use jQuery to grab them / read values.

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +        if (textField && typeof textField !== 'undefined') {
I think this can be simplified to 
```suggestion
        if (textField != null) {
```

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +      var emailSubscriptions = ['subscribe_to_company_newsletter', 'subscribe_to_blog', 'subscribe_to_hiring_insights', 'subscribe_to_events', 'subscribe_to_job_opportunities'];
These can stay snake_cased since they're text, not vars

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +        var emailSubscriptionCheckbox = document.querySelector("#" + emailSubscriptions[i]);
Same here as above

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +        url: 'https://9fdf-41-71-3-15.ngrok.io/api/growth/forms/community_activities',
Don't forget to remove ngrok

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +    $(document).on("click", ":input[type='submit']", function(e) {
Can get native element this way
```suggestion
    $(document).on("click", submitButton[0], function(e) {
```

2022-07-15 14:15 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +    $(document).on("click", ":input[type='submit']", function(e) {
If this doesn't work due to global targetting, double check if `:input` needs the `:` or not

2022-07-19 12:25 UTC, dominicaw approved these changes
nicely done 👌

2022-07-21 07:40 UTC, jethroflanagan commented on global/community-activities@1.0.js
> +        url: 'https://8226-41-71-27-131.ngrok.io/api/growth/forms/community_activities',
Please remove ngrok

2022-07-21 07:40 UTC, jethroflanagan approved these changes
Nicely done! Please drop ngrok, and it's all good to go

2022-07-22 09:11 UTC, merged