Employers scripts update for experiments
offerzen/webflow pull request #28
Opened 2022-07-29 11:53 UTC by chama-ram

Updated classes of phone number input fields and targeting the elements more specifically. 

This is to allow the experiment to run smoothly while have various forms in place. In order to set up the A/B Test in Google optimize, we need to make changes to the script to avoid any elements from clashing

2022-07-29 12:05 UTC, jethroflanagan requested changes
There are a number of elements that could be problematic if not scoped.

Recommend 2 "global" variables in the top of the function, e.g. `const ogForm =...` then use `ogForm.find('x')` and add another for multistep form

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +      fullList = $('.full-list');
Please scope

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +      $('.w-checkbox').each(function () {
Please scope

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +        if (el.find('input[type=checkbox]').is(':checked')) {
These are fine to leave once above version is scoped

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +          let form = $('#wf-Company-Lead-Form');
Should this be `#og-company-signup-form`?

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +      const form = $('#wf-Company-Lead-Form');
Check scoping

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +      $('#in-office-checkbox, #fully-remote-checkbox, #hybrid-checkbox').on(
Please scope

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +        $('#wf-Company-Lead-Form').on('submit', function (e) {
Check scoping

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5A.js
> +        const submitButton = $('#wf-Company-Lead-Form input[type=submit]');
Check scoping

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5B.js
> +      var source = $('.js-analytics-source').text();
Please scope

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5B.js
> +      $('.js-val-msg-roles').hide();
Please scope

2022-07-29 12:05 UTC, jethroflanagan commented on offerzen/global/employers/employers@5.5B.js
> +        $('.js-val-msg-roles').show();
Please scope

2022-07-29 13:21 UTC, chama-ram commented on offerzen/global/employers/employers@5.5A.js
> +      fullList = $('.full-list');
This is not part of the form

2022-08-01 09:35 UTC, jethroflanagan approved these changes

2022-08-01 11:17 UTC, michael616kriel approved these changes

2022-08-01 11:19 UTC, merged