MVP: New phone number input
offerzen/webflow pull request #36
Opened 2022-08-25 15:13 UTC by dominicaw

**Why:**
Intl tel input library did not have the level of flexibility we needed to create a mobile first phone input field. We have opted to move away from Intl tel input, in favour of a custom built phone field.

**What:**
I have taken the country codes object from Intl tel input library, removed unnecessary information and stored it. Select2 is using that information to create a dropdown with a search field.

2022-08-30 11:22 UTC, jethroflanagan requested changes
These changes should make it clearer as to the flow of code. Otherwise what it's doing looks good!

2022-08-30 11:22 UTC, jethroflanagan commented on offerzen/global/employers/employers@7.js
> +    const phoneNumberCountries = [
Please move this to the top of phone number input for clarity (just after the comment)

2022-08-30 11:22 UTC, jethroflanagan commented on offerzen/global/employers/employers@7.js
> +    });
Please move this into a function  - you can call it initializePhoneNumberField, or setupPhoneNumberField or similar

2022-08-30 11:22 UTC, jethroflanagan commented on offerzen/global/employers/employers@7.js
> +    });
Move this content into the above function, too, please

2022-08-30 11:22 UTC, jethroflanagan commented on offerzen/global/employers/employers@7.js
> +    });
Also move this into the initialize function

2022-08-30 11:22 UTC, jethroflanagan commented on offerzen/global/employers/employers@7.js
> +      addPhoneValidation(onPhoneFieldReady);
You can call your "initalize" function just before adding the validator

2022-08-31 08:20 UTC, chama-ram requested changes
Looks good! 👌👌Please update the script for the Experiment 1 lead form as well.

2022-08-31 08:22 UTC, jethroflanagan approved these changes
Great stuff!

2022-08-31 12:05 UTC, chama-ram approved these changes
Yay! Thank you for updating the scripts 🥇Looking goood!

2022-09-01 13:37 UTC, merged