Track GTM event when lead submission is successful
offerzen/webflow pull request #48
Opened 2022-11-02 10:30 UTC by chama-ram

Why ❓ ❓ ❓ 
Currently, a GTM event is being pushed on submit after validation has passed but before we receive a success response from the server side. 
As a result, the events count can be inaccurate for performance marketing platforms, specially since now we have Clearout validating the lead on the server side.

What Changed 🚧 
As an attempt to improve accuracy on events, we are moving the tracking of the GTM event to when the server returns success.

Removed trackSubmission from line 123 to line 143
Check out this screenshot to see what changed:
![Screenshot 2022-11-02 at 12 24 02](https://user-images.githubusercontent.com/82391266/199466780-421fa625-1ff9-40d3-b875-112cb6dc7535.png)

2022-11-02 14:15 UTC, jethroflanagan commented
Still investigating

2022-11-02 14:16 UTC, jethroflanagan requested changes
No changes, just investigating

2022-11-02 14:20 UTC, jethroflanagan requested changes
Please check the recommendation instead

2022-11-02 14:20 UTC, jethroflanagan commented on offerzen/global/employers/employers@9.0.js
> +        var isPlaywrightTest = emailValue.includes('playwrighttest');
```suggestion
        var isPlaywrightTest = emailValue.match(/^\s*playwrighttest@offerzen\.com\s*$/i) != null;
```

2022-11-02 14:20 UTC, jethroflanagan commented on offerzen/global/employers/employers@9.0.js
> +        var isPlaywrightTest = emailValue.includes('playwrighttest');
This will match things like `   playwrighttest@offerzen.com` but not `playwrighttest@blah.com`

2022-11-03 08:48 UTC, MarkusKuhn commented
@jethroflanagan: @chama-ram did add the requested change accordingly and tested it out. Approving for her while you're out

2022-11-03 08:48 UTC, merged