Enable company member to indicate what Skills they are Hiring for
offerzen/webflow pull request #9
Opened 2022-03-16 12:40 UTC by michael616kriel

https://offerzen.atlassian.net/jira/software/projects/GPS/boards/4?assignee=61309abdac61dc00696a26e4&selectedIssue=GPS-807

2022-03-25 11:09 UTC, MarkusKuhn approved these changes

2022-03-25 12:31 UTC, jethroflanagan requested changes
Are these files being used or is that issue where the CSS doesn't get loaded in Webflow still occurring?

2022-03-25 12:31 UTC, jethroflanagan commented on offerzen/global/employers/employers@1.0.js
> +      form = $('#wf-Company-Lead-Form')
```suggestion
      const form = $('#wf-Company-Lead-Form');
```
Otherwise it gets added to `window`

2022-03-25 12:31 UTC, jethroflanagan commented on offerzen/global/employers/employers@1.0.js
> +      var hiringSkills = []
Please use `const` or `let` where possible

2022-03-25 12:31 UTC, jethroflanagan commented on offerzen/global/employers/employers@1.0.js
> +        }*/
Can be removed

2022-03-25 12:31 UTC, jethroflanagan commented on offerzen/global/employers/employers@1.0.js
> +      input.value.replace(/[ \-\(\)]/g, '').replace(/\+([0-9]{2})|([0])/g, '')
This has the bug in it that's causing [GPS-951](https://offerzen.atlassian.net/browse/GPS-951)

2022-03-25 12:31 UTC, jethroflanagan commented on offerzen/global/employers/employers@1.0.js
> +        }*/
Can be removed

2022-03-28 09:16 UTC, jethroflanagan approved these changes

2022-03-28 09:16 UTC, merged